version: '3.8'

services:
  webapi:
    image: sasanarham/contact-manager:latest
    ports:
      - "8080:80"
    depends_on:
      - redis
      - sql_server
    environment:
      - DATABASE_NAME=ContactmanagerDB
      - DATABASE_SERVER=sql_server
      - DATABASE_PORT=1433
      - DATABASE_USER=sa
      - DATABASE_PASSWORD=MyStr0ngPassw0rd_1
      - CACHE_DATABASE_SERVER=redis
      - CACHE_SERVER_PORT=6379
      - EVENT_BUS_HOST_ADDRESS=amqp://guest:guest@rabbitmq:5672

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: MyStr0ngPassw0rd_1
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_TCP_PORT: "1433"
    ports:
      - "1432:1433"
  
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672" # you houd run this command on rabbimq teminal to be able to use management panl in browser: rabbitmq-plugins enable rabbitmq_management
