apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvclaim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      volume: redis-pv

      