apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    volume: redis-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.1
    path: "/redis"

