apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbit-pvclaim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Mi
  selector:
    matchLabels:
      volume: rabbit-pv


      