apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapi
  name: webapi-service
spec:
  selector:
    app: webapi
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP