apiVersion: v1
kind: Secret
metadata:
  name: webapi-secret
type: Opaque
stringData:
  MainDataBase__ServerName: "YourServerAddress"
  MainDataBase__Port: "1433"
  MainDataBase__DbName: "YourDbName"
  MainDataBase__Username: "YourUserName"
  MainDataBase__Password: "YourPassword"
  MongoDb__ConnectionString: "mongodb://localhost:27017"
  DistributedCacheDataBase__ServerName: "redis-service"
  DistributedCacheDataBase__Port: "6379"
  EVENT_BUS__HOST_ADDRESS: "amqp://guest:guest@rabbitmq:5672"
  EVENT_BUS__HOST_ADDRESS: "amqp://guest:guest@rabbit-service:5672"
  AzureApp__ASPNETCORE_ENVIRONMENT: "Development"
  AzureApp__AZURE_CLIENT_ID: "YourClientID"
  AzureApp__AZURE_TENANT_ID: "YourTenantID"
  AzureApp__AZURE_CLIENT_SECRET: "YourClientSecret"
  AzureApp__Key_Vault_Url: "YourvultUrl"
  AzureStorageConfigs__AccountName: "YourAccountName"
  AzureStorageConfigs__DefaultContainer: "contact-manager-container"